### ISSUE TITLE
[FORUM] Provide OAuth Login

### ISSUE THREAD

**Issue by ghost** [aionnetwork/docs#10]
("abusing" the docs repo to avoid filing this on main repo)

The AION forum (https://forum.aion.network) should provide an OAuth login.

It looks like the used "Discourse" supports this:

"
Standard authentication

Log in options include:

    Local log in
    Discourse Single sign-on
    Facebook, Google, Instagram, Twitter, Yahoo, and Github
"

https://payments.discourse.org/pricing

I assume that the Github&Twitter would cover most people.

**Comment by johnnymatthews** [comment]
Good suggestion, but it doesn't fit into this repo. Issues with the Aion forum should be listed in the forum itself. There's a specific section for this kind of thing: https://forum.aion.network/c/feedback

I'm gonna close this issue. @lazaridiscom, can you do me a favour and post this on the forum?

**Comment by ghost** [comment]
Nope!

(reread all this in a day or two, then ask yourself why I refused your plea that bluntly.)

## Note to readers

When team-members start to place "process over essence", treating contributors like "assistants", then things are very very bad.

Especially when the processes in place are either not existent or defective.

I am now "out here", and hope that you, the Management, realize that much work must be done (https://github.com/aionnetwork/aion/issues/792) to achieve "Engineering Excellence" within the overall AION Project, especially the public facing part.

cu!
