### ISSUE TITLE
void

### ISSUE THREAD

**Issue by ghost** [aionnetwork/docs#12]

**Comment by johnnymatthews** [comment]
I'm not sure what you mean @lazaridiscom. Are you saying there is this a formatting issue? The corresponding `.md` file is here: https://github.com/aionnetwork/docs/blob/master/aion-virtual-machine/_index.md

**Comment by lazaridiscom** [comment]
was to lazy for a screenshot, give me a few min.

**Comment by lazaridiscom** [comment]
Here we go:

top: as it is

bottom: as it should be

(it seems that this is in the publishing template, not the .md files)

![aion-doc-code-box](https://user-images.githubusercontent.com/46370091/53746027-fc4f6400-3ea8-11e9-8706-6f14829f0d5d.jpg)

**Comment by johnnymatthews** [comment]
Yeah, it looks like this is an issue with the way the Readme.io docs platform deals with code blocks. [_index.md](https://github.com/aionnetwork/docs/blob/master/aion-virtual-machine/_index.md) matches the [Markdown Rules](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md).

**Comment by lazaridiscom** [comment]
should be either fixable (template), or they should provide it as support (i remember its a paid service? ).
