### ISSUE TITLE
dApp and Dapp are used interchangeably

### ISSUE THREAD

**Issue by fulldecent** [aionnetwork/docs#36]
In the documentation, dApp and Dapp are used interchangeably.

Documentation will be improved if the word styling is consistent and only one of the two variants is mentioned.

**Comment by johnnymatthews** [comment]
Good call. I ran a quick find-and-replace for `dApp` and `DApp`. Everything should now be `Dapp`, ignoring URLs.

de819696ed21c951a0a45e4f08398994665dbbc1

Let me know if you notice other ones I've missed.
