### ISSUE TITLE
Missing `Variable types` for Tools-Maven/IntelliJ

### ISSUE THREAD

**Issue by jennijuju** [aionnetwork/docs#47]
**Is your feature request related to a problem? Please describe.**
We need to add `variable types` page for maven and intellilj to explain the selector and format for `-Dargs`

**Additional context**
Migrate this page: https://docs.aion.network/docs/variable-types

**Comment by johnnymatthews** [comment]
Fixed in aef981dec331272302c142a44ba04edd82ee322a
