### ISSUE TITLE
Add "end-to-end" section to Maven documentation.

### ISSUE THREAD

**Issue by fulldecent** [aionnetwork/docs#50]
Current the maven documentation at https://github.com/aionnetwork/docs/tree/modular/developers/tools/maven-cli does not include an end-to-end section.

Please add this section and have it include performing the included tests.

**Comment by johnnymatthews** [comment]
There's a task in the backlog for this. Thanks for bringing it up, it'll get tackled next sprint.

**Comment by johnnymatthews** [comment]
Completed in aef981dec331272302c142a44ba04edd82ee322a

**Comment by fulldecent** [comment]
Looks great, thank you
