### ISSUE TITLE
Each page load resets the left navigation state

### ISSUE THREAD

**Issue by fulldecent** [aionnetwork/docs#51]
In the modular branch. Each time you load a page (click a link on the left) the navigation state is reset and any opened branches on the left are reset.

This could be fixed by:

1) Automatically opening the section of the loaded page; or
2) Using cookies to track each sections open/close state; or
3) Use History API to fake page loads

Recommending option 1 at this time.

**Comment by jennijuju** [comment]
This issue is in our backlog.

**Comment by johnnymatthews** [comment]
This issue has now been fixed.
