### ISSUE TITLE
Explain how to use Maven archetype

### ISSUE THREAD

**Issue by fulldecent** [aionnetwork/docs#55]
https://docs.aion.network/docs/maven-and-aion4j

Currently there is:

> More information on Maven archetypes specifically can be found on the Apache Maven website.

It will be very helpful to add:

> To get started using the Aion4j archetype, do this...

**Comment by fulldecent** [comment]
Also, if this code https://github.com/bloxbean/avm-archetype is official then why is it not hosted on https://github.com/aionnetwork/

**Comment by fulldecent** [comment]
Solution: add this code snippet:

```
mvn archetype:generate -DarchetypeGroupId=org.aion4j -DarchetypeArtifactId=avm-archetype -DarchetypeVersion=0.20
```

**Comment by johnnymatthews** [comment]
That snippet of code can be found [here on the live site](https://docs.aion.network/docs/maven-and-aion4j-create-a-project), and [here in the docs repo](https://github.com/aionnetwork/docs/blob/modular/developers/tools/maven-cli/create-a-project.md), both under the _Create a Project_ section.

Using Maven, what archetypes are, and how they exist will all be tackled in the Maven End-to-End guide #50 .

**Comment by johnnymatthews** [comment]
I'm marking this issue as closed since the information is available within the docs, and no further comments have been added. @fulldecent please feel free to re-open the issue and provide further comments if you think this issue isn't resolved.

**Comment by fulldecent** [comment]
Great, thank you
