### ISSUE TITLE
Increase Contrast of Documentation Site

### ISSUE THREAD

**Issue by ghost** [aionnetwork/docs#6]
https://docs.aion.network/docs

The overall look&feel is nice, with the exception of the low contrast of navigation and content.

The contrast should be increased.

(Obvious rationale: Documentation sites are not about design, but about readability)

**Comment by johnnymatthews** [comment]
The side-menu links and body text have been changed to darker colours to make things more readable.

**Comment by ghost** [comment]
Confirming: readability is better now.
