### ISSUE TITLE
Does this repo contain the exact live version of the documentation site?

### ISSUE THREAD

**Issue by ghost** [aionnetwork/docs#7]
The live site (https://docs.aion.network/docs) has

>New Docs Website!
>We've got a brand new documentation site come to you very soon! It's in beta right now and you can >check it out here.

on top of the index page.

The index page within this repo

https://github.com/aionnetwork/docs/blob/master/_index.en.md

does not contain it.

Does this repo here contain the exact live version of the documentation site?

**Comment by johnnymatthews** [comment]
No. This repo is not pulled in by our current documentation provider automatically. This repo feeds the [beta site](aiondocs.netlify.com). This repo was created for the sole purpose of managing the beta documentation site.
